---
ruby_opts: &ruby_opts
  LDFLAGS: "-L/opt/X11/lib"
  RUBY_CONFIGURE_OPTS: "--enable-shared --with-openssl-dir=/opt/boxen/homebrew/opt/openssl --with-readline-dir=/opt/boxen/homebrew/opt/readline"
ruby::version::env:
  1.9.3-p545:
    <<: *ruby_opts
  2.0.0-p481:
    <<: *ruby_opts
  2.1.2:
    <<: *ruby_opts
ruby::global_version: "2.1.2"
ruby::default_gems:
  - bundler
  - rubygems-update
  - pry
  - tmuxinator
  - vvm-rb
  - refe2
  - rubocop
ruby::build::ensure: 'v20140509.1'
ruby::rbenv_plugins:
  rbenv-binstubs:
    ensure: 1.3
    source: ianheggie/rbenv-binstubs
  rbenv-ctags:
    ensure: v1.0.1
    source: tpope/rbenv-ctags
