---
ruby::global::version: 2.0.0-p353
ruby::default_gems:
  - bundler
  - rake
  - rubygems-update
  - rbenv-rehash
  - pry
  - tmuxinator
  - vvm-rb
ruby::rbenv_plugins:
  rbenv-binstubs:
    ensure: 1.3
    source: ianheggie/rbenv-binstubs
  rbenv-ctags:
    ensure: master
    source: tpope/rbenv-ctags
