---
ruby::rbenv_version: master
ruby::version::env:
  1.9.3:
    CONFIGURE_OPTS: "--enable-shared --with-openssl-dir=/opt/boxen/homebrew/opt/openssl --with-readline-dir=/opt/boxen/homebrew/opt/readline"
  2.0.0:
    RUBY_CONFIGURE_OPTS: "--enable-shared --with-openssl-dir=/opt/boxen/homebrew/opt/openssl --with-readline-dir=/opt/boxen/homebrew/opt/readline"
  2.1.0:
    RUBY_CONFIGURE_OPTS: "--enable-shared --with-openssl-dir=/opt/boxen/homebrew/opt/openssl --with-readline-dir=/opt/boxen/homebrew/opt/readline"
ruby::default_gems:
  - bundler
  - rake
  - rubygems-update
  - rbenv-rehash
  - pry
  - tmuxinator
  - vvm-rb
ruby::rbenv_plugins:
  ruby-build:
    ensure: master
    source: sstephenson/ruby-build
  rbenv-default-gems:
    ensure: master
    source: sstephenson/rbenv-default-gems
  rbenv-binstubs:
    ensure: master
    source: ianheggie/rbenv-binstubs
  rbenv-ctags:
    ensure: master
    source: tpope/rbenv-ctags
