---
ruby::ruby_env:
  CONFIGURE_OPTS: "--with-openssl-dir=/opt/boxen/homebrew/opt/openssl --enable-shared --with-readline-dir=/opt/boxen/homebrew/opt/readline"
  RUBY_CONFIGURE_OPTS: "--with-openssl-dir=/opt/boxen/homebrew/opt/openssl --enable-shared --with-readline-dir=/opt/boxen/homebrew/opt/readline"
ruby::default_gems:
  - bundler
  - rake
  - rubygems-update
  - rbenv-rehash
  - pry
  - tmuxinator
  - vvm-rb
ruby::rbenv_plugins:
  rbenv-default-gems:
    ensure: master
    source: sstephenson/rbenv-default-gems
  rbenv-binstubs:
    ensure: master
    source: ianheggie/rbenv-binstubs
  rbenv-ctags:
    ensure: master
    source: tpope/rbenv-ctags
